### ISSUE TITLE
Before calling `createReduxContainer`, please call `createReactNavigationReduxMiddleware`, so that we know when to trigger your listener.

### ISSUE THREAD

**Issue by koutily** [react-navigation/react-navigation-redux-helpers#76] opened 2019-02-13 09:27 UTC

**Comment by koutily** [comment] 2019-02-13 09:27
import Routers from "../Routers/Router";
import {createNavigationReducer,createReactNavigationReduxMiddleware,createReduxContainer,} from "react-navigation-redux-helpers"

import {connect} from "react-redux"


const middleware=createReactNavigationReduxMiddleware(
    "root",
    state=>state.navigation
)


const AppNavigator=createReduxContainer(Routers,"root");
export  {AppNavigator,middleware}

**Comment by koutily** [comment] 2019-02-13 10:02
After some changes i am not getting this error but iam getting the another error called Cannot read property 'getStateForAction' of undefined

**Comment by simranaurora-evive** [comment] 2019-02-13 13:16
I am also getting the same error

**Comment by Ashoat** [comment] 2019-02-13 13:27
Since like most NPM packages we follow semver, you can expect that any major-version release will have breaking changes. Next time please do not upgrade without first checking what those breaking changes are. You can find them [https://github.com/react-navigation/react-navigation-redux-helpers/releases/tag/3.0.0](here). 

If you still have any issue after reading the breaking changes and adjusting your code accordingly, and want me to debug your code for you, you’ll need to provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.

**Comment by Ashoat** [comment] 2019-02-13 13:27
Closing this now since it seems like the issue will be resolved after reading the changelog linked above.

**Closed by Ashoat** 2019-02-13 13:27 UTC

**Comment by simranaurora-evive** [comment] 2019-02-13 13:36
I have gone through the breaking changes and installed react-navigation/core but it's still not working

**Comment by Ashoat** [comment] 2019-02-13 14:05
Try going through the breaking changes again, this time very carefully.

**Comment by Cawfree** [comment] 2019-03-06 12:56
I think [Ashoat](https://github.com/Ashoat) is hinting towards the fact that the `key` parameter is now _optional_. 

```
createReactNavigationReduxMiddleware(
  //key: string,
   state => state.nav,
);
```

**Comment by andrewazevedo** [comment] 2019-03-11 20:26
I just remove the key from `createReactNavigationReduxMiddleware` and now works fine.

**Comment by KoheiTigers** [comment] 2019-06-06 04:11
I am still getting

`navStateSelector is not a function (In 'navStateSelector(newState)', 'navStateSelector' is "root")]
- node_modules\react-navigation-redux-helpers\src\middleware.js:46:32 in <unknown>
- node_modules\redux-persist\lib\persistStore.js:69:21 in rehydrate
- node_modules\redux-persist\lib\persistReducer.js:73:27 in _rehydrate
- node_modules\redux-persist\lib\persistReducer.js:98:21 in <unknown>
- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:25 in <unknown>
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:152:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:200:17 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:464:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:320:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:17 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue`

**Comment by iceuncle** [comment] 2019-08-07 07:45
The `key` now is the second parameter, and is optional.

```
export function createReactNavigationReduxMiddleware<S>(
    navStateSelector: (state: S) => NavigationState,
    key?: string,
  ): Middleware;

createReactNavigationReduxMiddleware(
   state => state.nav,
   key: string
);
```

**Comment by MriduDixit15** [comment] 2019-08-26 13:14
> 
> 
> I am still getting
> 
> `navStateSelector is not a function (In 'navStateSelector(newState)', 'navStateSelector' is "root")]
> 
>     * node_modules\react-navigation-redux-helpers\src\middleware.js:46:32 in
> 
>     * node_modules\redux-persist\lib\persistStore.js:69:21 in rehydrate
> 
>     * node_modules\redux-persist\lib\persistReducer.js:73:27 in _rehydrate
> 
>     * node_modules\redux-persist\lib\persistReducer.js:98:21 in
> 
>     * node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
> 
>     * node_modules\promise\setimmediate\core.js:123:25 in
> 
>     * node_modules\react-native\Libraries\Core\Timers\JSTimers.js:152:14 in _callTimer
> 
>     * node_modules\react-native\Libraries\Core\Timers\JSTimers.js:200:17 in _callImmediatesPass
> 
>     * node_modules\react-native\Libraries\Core\Timers\JSTimers.js:464:30 in callImmediates
> 
> 
>     * [native code]:null in callImmediates
> 
> 
>     * node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:320:6 in __callImmediates
> 
>     * node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in
> 
>     * node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297:10 in __guard
> 
>     * node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:17 in flushedQueue
> 
> 
>     * [native code]:null in flushedQueue
> 
>     * [native code]:null in invokeCallbackAndReturnFlushedQ
same problem +1
how you solved

**Comment by juzhax** [comment] 2019-09-18 03:54
`
import {
  createReactNavigationReduxMiddleware,
  createReduxBoundAddListener,
  createReduxContainer,
} from 'react-navigation-redux-helpers';

const middleware = createReactNavigationReduxMiddleware(
 navStateSelector => "root",
state => state.navReducer,
);

const addListener = createReduxContainer("root");

export {
  middleware,
  addListener,
};
`


navStateSelector => "root",

**Comment by shengbenqiang** [comment] 2019-10-22 06:19
> 我正在获取navStateSelector不是函数

参数的位置在新版本被改了，你可以看看依赖文件里位置，两者交换了，只要交换后就没问题了

**Comment by bunyaminmrcn** [comment] 2019-11-13 18:31
Error Still continue. Topic must be reopen .
