### ISSUE TITLE
reduxifyNavigator is causing this.props.navigation.addListener('didFocus') to not work

### ISSUE THREAD

**Issue by diegoddox** [react-navigation/react-navigation-redux-helpers#53] opened 2018-07-20 08:19 UTC
**First thanks for the lib.**

**Description**
I encounter a strange behavior while upgrading to `react-navigation@2`. Following the example in the docs I noticed that the `navigation.AddListener('didFcous'` was not working on every screen.

After many hours of debugging, I found out that by removing the `reduxifyNavigator` all screen that was listening for the event `didFocus` was working normally.

**The issue**
This accour when you have a screen that is listening for `didFcous/some other events` and is connected to redux and by `dispatching` an action inside of the first `didFocus` the next `didFcous` on the stack will not work.

I've used some time to create a repo that can reproduce this issue.
https://github.com/diegoddox/navigation-redux-helper

This is the file that you wanna take a look.
https://github.com/diegoddox/navigation-redux-helper/blob/master/Route.js

**dependencies.**
react: 16.4.1
react-native: 0.54.0 | 0.56.0
react-navigation: 2.6.2 | 2.8.0
react-navigation-redux-helpers: 2.0.2
react-redux: 5.0.7
redux: 4.0.0

**Comment by Ashoat** [comment] 2018-07-20 21:51
I think I have fixed this in `react-navigation-redux-helpers@2.0.3`. Please give it a try and let me know if it works.

**Comment by diegoddox** [comment] 2018-07-23 01:29
It's working but there is a bug with the current fix, I've made a PR that should fix it #54

**Comment by Ashoat** [comment] 2018-07-26 17:15
Any luck @diegoddox?

**Comment by diegoddox** [comment] 2018-07-27 08:44
Hi @Ashoat sorry I haven't had the time yet

**Comment by javierbustamante** [comment] 2018-08-20 11:31
Hi, I'm also suffering the issue...
I add listeners for willFocus, willBlur, didFocus and for didBlur but none works...
I'm working with the version 2.0.5.

**Comment by mmarvick** [comment] 2018-10-02 15:51
Hey @Ashoat - I'm running into the same issue and did verify that #60 fixed it for me locally. I'm on react-navigation 2.4.1 and react-navigation-redux-helpers 2.0.5. I'll see if I can put together a repo with a repro later today.

**Comment by shyaniv7** [comment] 2018-10-09 22:31
https://github.com/xxyan0205/react-navigation-redux-helpers/commit/b7299f5b3ad22ef8c9ae1903b184fc20f4583ac9

fixes the issue for me.
Using react-navigation 2.17 and redux-helpers 2.0.6

adding the timeout around didUpdateCallback works

```
setTimeout(() => {
  didUpdateCallback();
}, 0);
```

@Ashoat can you please merge it and release a new version?

**Comment by Ashoat** [comment] 2018-10-10 17:17
Hey guys - the fix in https://github.com/xxyan0205/react-navigation-redux-helpers/commit/b7299f5b3ad22ef8c9ae1903b184fc20f4583ac9 is to gate the `didUpdateCallback` behind a `setTimeout` call. This seems to indicate that `didUpdateCallback` is firing too early.

The problem with the fix is that it is brittle. It may work on your simulators, but will it work on physical devices? On old devices? A new version of React Native or React Navigation might make it break, or force us to increase the timeout value.

The real solution is to figure out why calling `didUpdateCallback` immediately in `componentDidUpdate` doesn't work, and what needs to happen first. Then we can update the code to call `didUpdateCallback` exactly when it needs to.

I am willing to investigate this issue and try to figure out what the right solution is. If the `setTimeout` is the only thing that works, I will merge it (though I doubt that).

But first, I need either an Expo Snack or a repro that has a minimal project that reproduces the issue. This is an expectation in the React Navigation org, and in the broader React Native ecosystem. It is nigh-on impossible to debug and fix issues when you aren't able to reproduce them.

To be absolutely clear: if you want a fix for this issue to be merged, then please take the time to create either an Expo Snack or a repo that reproduces the issue. Copy-pasting code will not suffice, not will linking me to your existing project.

**Comment by shyaniv7** [comment] 2018-10-10 18:36
hey @Ashoat,

here is an example that I found on a different thread that should be sufficient for your investigation
https://snack.expo.io/@mrloh/tabnavigator-with-redux-didfocus

**Comment by Ashoat** [comment] 2018-10-10 19:18
@shyaniv7, you've linked to a Snack that is using an outdated version of this package, and that is demonstrating a related but distinct issue that has long been fixed.

**Comment by shyaniv7** [comment] 2018-10-10 19:38
@Ashoat 💩  I apologize, this is the wrong link. I cannot find the example I saw a few days ago

**Comment by mmarvick** [comment] 2018-10-10 22:12
I had trouble making a repro-able case when I tried last week, for what it's worth. I tried building something from scratch using all the same packages and package versions and didn't get the buggy behavior, so there's something more subtle going on than just a bad combination of dependency versions.

I'll try going the other direction (taking my app and breaking it down to a simple repro case), but it might be a while before I get a chance -- so if somebody else has time and beats me to it, please do.

**Comment by ddthuan87** [comment] 2018-12-21 09:58
Hi @Ashoat! 

this issue has been fixed?

**Comment by Ashoat** [comment] 2018-12-21 16:46
The original reported issue was fixed. The second reported issue still doesn’t have a repro. There is a hack in #60 that may help avoid the second issue if you’re experiencing it.

**Comment by ddthuan87** [comment] 2018-12-24 03:08
i'm using this tut and not word @Ashoat 

```
componentDidUpdate(){
        setTimeout(() => {
            this.props.navigation.addListener('didFocus', () => {
                this._handleDefaultLoad();
            });
        }, 0);
    }	     
```

**Comment by Ashoat** [comment] 2018-12-24 03:38
I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.

**Comment by ivan-kaminskyi** [comment] 2019-01-14 15:44
I am alose experiencing this issue randomly. Can`t find out the exact reason. On some screens it does work as expected, but on the others they don`t within the same navigator. Hope this will be fiixed soon.

**Comment by bencergazda** [comment] 2019-02-20 16:26
@Ashoat I am facing with the same issue. I am using Infinite Red's Ignite boilerplate (Andross), and the issue exists on a completely clean install. I created a somewhat MCVE (a clean Ignite Andross install), you can find it on https://github.com/bencergazda/react-navigation-redux-helpers-issue-53

I could not catch any event at all, but the implementation looks to be OK. Could you please have a look at it?

**Comment by Ashoat** [comment] 2019-02-20 17:23
Are you able to reproduce without Ignite? If yes, can you put up an MCVE (as specified above, either through Expo Snack or `react-native init`). If not, I'd guess it has something to do with the interplay with Ignite?

**Comment by Oscarz90** [comment] 2019-03-28 04:12
has it been well tested?? Im facing the same problem u.u please help

> setTimeout(() => {
>             this.props.navigation.addListener('didFocus', () => {
>                 this._handleDefaultLoad();
>             });
>         }, 0);

**Closed** 2019-04-29 14:38 UTC

**Comment by parkhanseong** [comment] 2019-05-02 07:48
> has it been well tested?? Im facing the same problem u.u please help
> 
> > setTimeout(() => {
> > this.props.navigation.addListener('didFocus', () => {
> > this._handleDefaultLoad();
> > });
> > }, 0);

mee too

**Comment by mo6moming** [comment] 2019-05-16 06:57
> @Ashoat I am facing with the same issue. I am using Infinite Red's Ignite boilerplate ([Andross](https://github.com/infinitered/ignite-andross)), and the issue exists on a completely clean install. I created a somewhat MCVE (a clean Ignite Andross install), you can find it on https://github.com/bencergazda/react-navigation-redux-helpers-issue-53
> 
> I could not catch any event at all, but the implementation looks to be OK. Could you please have a look at it?
> 
> By default Andross uses `react-navigation@3.0.0` and `react-navigation-redux-helpers@2.0.9`, but upgrading to `react-navigation@3.3.0` and `react-navigation-redux-helpers@3.0.0` still doesn't help.

FYR: I tried below and it works : 
- ReduxNavigation.js , export Middleware instead of just createReactNavigationReduxMiddleware
```
export const appNavigatorMiddleware = createReactNavigationReduxMiddleware(
  'root',
  (state) => state.nav
)
```
- then import to CreateStore.js and modify as below.
```
import {appNavigatorMiddleware} from '../Navigation/ReduxNavigation'

/* ------------- Navigation Middleware ------------ */
  // const navigationMiddleware = createReactNavigationReduxMiddleware(
  //   'root',
  //   state => state.nav
  // )
  // middleware.push(appNavigatorMiddleware)
  middleware.push(appNavigatorMiddleware)
```

**Comment by superp** [comment] 2019-05-20 09:17
> > @Ashoat I am facing with the same issue. I am using Infinite Red's Ignite boilerplate ([Andross](https://github.com/infinitered/ignite-andross)), and the issue exists on a completely clean install. I created a somewhat MCVE (a clean Ignite Andross install), you can find it on https://github.com/bencergazda/react-navigation-redux-helpers-issue-53
> > I could not catch any event at all, but the implementation looks to be OK. Could you please have a look at it?
> > By default Andross uses `react-navigation@3.0.0` and `react-navigation-redux-helpers@2.0.9`, but upgrading to `react-navigation@3.3.0` and `react-navigation-redux-helpers@3.0.0` still doesn't help.
> 
> FYR: I tried below and it works :
> 
> * ReduxNavigation.js , export Middleware instead of just createReactNavigationReduxMiddleware
> 
> ```
> export const appNavigatorMiddleware = createReactNavigationReduxMiddleware(
>   'root',
>   (state) => state.nav
> )
> ```
> 
> * then import to CreateStore.js and modify as below.
> 
> ```
> import {appNavigatorMiddleware} from '../Navigation/ReduxNavigation'
> 
> /* ------------- Navigation Middleware ------------ */
>   // const navigationMiddleware = createReactNavigationReduxMiddleware(
>   //   'root',
>   //   state => state.nav
>   // )
>   // middleware.push(appNavigatorMiddleware)
>   middleware.push(appNavigatorMiddleware)
> ```

You save my life! :)
I had a problem with black screen camera after switching tab, and now it works!

**Comment by clerecudzio** [comment] 2019-05-26 13:26
> > @Ashoat I am facing with the same issue. I am using Infinite Red's Ignite boilerplate ([Andross](https://github.com/infinitered/ignite-andross)), and the issue exists on a completely clean install. I created a somewhat MCVE (a clean Ignite Andross install), you can find it on https://github.com/bencergazda/react-navigation-redux-helpers-issue-53
> > I could not catch any event at all, but the implementation looks to be OK. Could you please have a look at it?
> > By default Andross uses `react-navigation@3.0.0` and `react-navigation-redux-helpers@2.0.9`, but upgrading to `react-navigation@3.3.0` and `react-navigation-redux-helpers@3.0.0` still doesn't help.
> 
> FYR: I tried below and it works :
> 
> * ReduxNavigation.js , export Middleware instead of just createReactNavigationReduxMiddleware
> 
> ```
> export const appNavigatorMiddleware = createReactNavigationReduxMiddleware(
>   'root',
>   (state) => state.nav
> )
> ```
> 
> * then import to CreateStore.js and modify as below.
> 
> ```
> import {appNavigatorMiddleware} from '../Navigation/ReduxNavigation'
> 
> /* ------------- Navigation Middleware ------------ */
>   // const navigationMiddleware = createReactNavigationReduxMiddleware(
>   //   'root',
>   //   state => state.nav
>   // )
>   // middleware.push(appNavigatorMiddleware)
>   middleware.push(appNavigatorMiddleware)
> ```

Superb. You saved me a thousand of minutes breaking this problem

**Comment by flyskywhy** [comment] 2020-04-28 06:34
https://github.com/shyaniv7/react-navigation/commit/20594229df37a9a08c8a8f117b680498365f1316 mentioned in https://github.com/react-navigation/react-navigation/issues/4670#issuecomment-404299410 works for me.
